apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: grafana-backendconfig
  namespace: monitoring
spec:
  healthCheck:
    checkIntervalSec: 10 
    timeoutSec: 1         
    healthyThreshold: 1   
    unhealthyThreshold: 3 
    requestPath: "/api/health" 
    port: 3000            

