apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana-health-check-policy
  namespace: monitoring
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 3
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 3000
        requestPath: /api/health
  targetRef:
    group: ""
    kind: Service
    name: my-grafana
