apiVersion: v1
kind: Service
metadata:
  name: todo-service
  annotations:
    cloud.google.com/backend-config: '{"default": "http-hc-config"}'
spec:
  type: clusterIP
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

